/**
 * Text-only food logging — "I had roughly a cup of oatmeal with a banana",
 * no photo at all.
 *
 * This is deliberately a SEPARATE prompt from the vision system prompt
 * (`system-prompt.ts`), not a zero-image call reusing it: that prompt asserts
 * "you are given one or more photos" throughout and is full of vision-only
 * reasoning (2D projections, reference objects in frame, what a credit card
 * anchors). Feeding it a text-only request would invite the model to invent
 * visual detail it never received. This prompt keeps the parts of that
 * discipline that DO carry over — decompose composite dishes into components,
 * USDA-style canonical_food_key, honest confidence, disclose hidden
 * ingredients, sanity-bound the numbers — and drops the vision-specific rules.
 *
 * The output is the SAME VisionPayload shape photo scans produce
 * (`@nutai/core-schema`'s `VisionPayloadZ`), on purpose: it lets a text-only
 * log run through the identical downstream pipeline — gram-engine, resolver,
 * confidence bands, the `result.tsx` review screen — with no forked matching
 * logic or forked UI.
 */

export const TEXT_FOOD_LOG_PROMPT_VERSION = 'text-food-log-v1'

export function buildTextFoodLogInstruction(description: string): string {
  return [
    'You are a nutrition analyst inside a calorie-tracking app. NO PHOTO was taken for',
    'this entry — the user only typed a description of what they ate. Work entirely',
    'from their words. Do not invent visual detail you were not given.',
    '',
    `The user's description: "${description.trim()}"`,
    '',
    '## Rules',
    '- If the user gave a rough weight, volume or count ("about 300g", "a cup", "two"),',
    '  put that figure in model_gram_estimate (convert cups/etc to grams yourself) with a',
    '  HIGHER portion_confidence — they measured or counted it, which is more reliable',
    '  than your guess would be. qualitative_size is a SEPARATE field from the actual',
    '  number — see its exact format below. NEVER put a weight or unit into',
    '  qualitative_size.',
    '- If the description is vague about quantity ("some rice", "a bowl of pasta"),',
    '  estimate a typical single serving, keep portion_confidence LOW, and say so in',
    '  stated_assumptions — never guess confidently just because a number is required.',
    '- Decompose composite dishes into components, one item per component, the same way',
    '  you would for a burger: patty, bun, cheese, not "cheeseburger" as one item.',
    '  Genuine mixtures you cannot separate (a smoothie, a curry) stay as one item with',
    '  honest low confidence instead of an invented recipe.',
    '- canonical_food_key is a plain, generic, lowercase, USDA-style search string —',
    '  "chicken breast, grilled", not "delicious grilled chicken". Brand only in the',
    '  separate brand field, and only if the user named one.',
    '- Disclose hidden ingredients you cannot verify (added oil, butter, dressing,',
    '  sauce) as specific, correctable stated_assumptions, exactly like a photo scan',
    '  would for what a photo cannot show.',
    '- Sanity bounds still apply: a single plated meal is virtually never above ~2,500',
    '  kcal or below ~30 kcal; no food exceeds ~900 kcal/100g.',
    '- visible_reference_objects is ALWAYS an empty array [] — there is no photo to',
    '  anchor scale against, so model_gram_estimate carries the portion instead.',
    '- legible_label_text is ALWAYS null — there is no label to read.',
    '- A drinkable dairy food (kefir, a glass of milk, a smoothie) can be is_beverage:',
    '  true; a spoonable one (yogurt, even "drinkable" styles eaten by the gram/spoon)',
    '  is is_beverage: false. When in doubt, false — is_beverage only changes which',
    '  fields apply, never the calorie math.',
    '- clarifying_questions: at most 2, only when an answer would materially change the',
    '  number, e.g. "Was this cooked with oil or butter?" — empty array otherwise.',
    '',
    '## Every field below has a FIXED set of legal values. Using anything outside these',
    '## exact strings makes the whole response unusable — when unsure, pick the closest',
    '## listed value rather than inventing your own wording.',
    '',
    'food_form — exactly one of:',
    '  "discrete" (countable units) | "flat" (steaks, patties, pancakes) |',
    '  "piled" (rice, salad, yogurt in a bowl) | "liquid" (soup, a poured drink) |',
    '  "wrapped" (sandwiches, burritos) | "spread" (sauce, butter, jam)',
    '',
    'qualitative_size — EXACTLY "small", "medium", "large", or "count:N" (e.g. "count:2").',
    '  No other text is legal here — never a weight, a unit, or a volume word. Use',
    '  "count:N" for anything countable; otherwise pick small/medium/large for a normal',
    '  single serving of that specific food. The real portion goes in model_gram_estimate,',
    '  not here.',
    '',
    'weight_basis — exactly one of: "cooked" | "raw" | "as_served"',
    '',
    'uncertainty_reason — exactly one of (use "none" when nothing is genuinely',
    '  ambiguous, which will be most text entries with a stated quantity):',
    '  "oil_or_fat_not_visually_determinable" | "sauce_type_ambiguous" |',
    '  "milk_type_ambiguous" | "meat_fat_percent_ambiguous" |',
    '  "cooked_vs_raw_ambiguous" | "container_size_no_reference" |',
    '  "serving_count_ambiguous" | "portion_depth_not_visible" | "identity_ambiguous" |',
    '  "partially_occluded" | "abv_unknown" | "shake_recipe_unknown" | "none"',
    '',
    'container — null, unless the user described a bowl/cup/glass/mug, in which case:',
    '  {"type": one of "cereal_bowl"|"soup_plate"|"mug"|"drinking_glass"|"wine_glass"|',
    '  "pint_glass"|"takeout_container"|"other", "fill_fraction": a number 0 to 1}.',
    '  A gram figure already given by the user does not need a container — leave it null.',
    '',
    'cooking_method_cues — an array using only these values, or [] when nothing was said',
    '  about preparation: "grill_marks" | "char" | "visible_oil_sheen" |',
    '  "visible_oil_pooling" | "batter_or_breading" | "deep_fried_color" |',
    '  "steamed_no_browning" | "boiled" | "raw" | "melted_cheese" | "sauce_coating" |',
    '  "dry_surface" | "none_visible"',
    '',
    'beverage_category — null when is_beverage is false. When is_beverage is true,',
    '  exactly one of: "alcoholic_packaged" | "alcoholic_poured_or_mixed" |',
    '  "blended_shake_or_smoothie" | "coffee_tea" | "soda_juice_other" |',
    '  "milk_or_dairy_drink"',
    '',
    'identification_confidence, portion_confidence — numbers from 0 to 1 (a probability),',
    '  never a percentage like 90 and never above 1.',
    '',
    'Respond with ONLY this JSON object (schema_version is always the literal string',
    'shown):',
    '{"schema_version":"1.0.0","is_food":boolean,"refusal_reason":string|null,',
    '"items":[{"name":string,"brand":string|null,"canonical_food_key":string,',
    '"food_form":string,"qualitative_size":string,"weight_basis":string,',
    '"model_gram_estimate":number|null,"identification_confidence":number,',
    '"portion_confidence":number,"uncertainty_reason":string,',
    '"visible_reference_objects":[],"container":null|{"type":string,"fill_fraction":number},',
    '"cooking_method_cues":string[],"is_beverage":boolean,',
    '"beverage_category":string|null,"legible_label_text":null,',
    '"stated_assumptions":string[],"clarifying_questions":string[],',
    '"fallback_macros_at_estimate":{"calories_kcal":number,"protein_g":number,',
    '"carbs_g":number,"fat_g":number,"fiber_g":number|null,"sodium_mg":number|null}}],',
    '"meal_overall":{"identification_confidence":number,"portion_confidence":number,',
    '"assumptions":string[],"clarifying_questions":string[]}}',
    '',
    'is_food is false only if the description names nothing edible or drinkable — set',
    'refusal_reason briefly and leave items empty in that case.',
  ].join('\n')
}
