import type { DbAdapter, RunResult, SqlValue } from '@nutai/db-adapter'
import * as SQLite from 'expo-sqlite'
import { NUTRITION_DB_BUILT_AT } from './nutrition-version'

/**
 * The expo-sqlite implementation of the shared DbAdapter interface.
 *
 * This file lives in apps/mobile and NOT in @nutai/db-adapter, deliberately.
 * `packages/*` must stay importable under bare Node with zero React Native
 * surface (PLAN.md §4.1) so the eval harness can run the real pipeline; an
 * `import 'expo-sqlite'` in that package would fail the node-purity gate. This
 * app is the only place allowed to hold React Native imports.
 *
 * The Node implementation lives at @nutai/db-adapter/node. Both satisfy the same
 * interface, which is what makes "it worked in the harness" mean something on
 * device.
 */
class ExpoDbAdapter implements DbAdapter {
  constructor(private readonly db: SQLite.SQLiteDatabase) {}

  async all<T = Record<string, SqlValue>>(sql: string, params: readonly SqlValue[] = []): Promise<T[]> {
    return (await this.db.getAllAsync(sql, params as SQLite.SQLiteBindValue[])) as T[]
  }

  async get<T = Record<string, SqlValue>>(sql: string, params: readonly SqlValue[] = []): Promise<T | null> {
    return ((await this.db.getFirstAsync(sql, params as SQLite.SQLiteBindValue[])) as T | null) ?? null
  }

  async run(sql: string, params: readonly SqlValue[] = []): Promise<RunResult> {
    const r = await this.db.runAsync(sql, params as SQLite.SQLiteBindValue[])
    return { changes: r.changes, lastInsertRowId: r.lastInsertRowId }
  }

  async exec(sql: string): Promise<void> {
    await this.db.execAsync(sql)
  }

  async transaction<T>(fn: (tx: DbAdapter) => Promise<T>): Promise<T> {
    let result!: T
    await this.db.withTransactionAsync(async () => {
      result = await fn(this)
    })
    return result
  }

  async close(): Promise<void> {
    await this.db.closeAsync()
  }
}

/** The writable user database. */
export async function openUserDb(): Promise<DbAdapter> {
  const db = await SQLite.openDatabaseAsync('user.db')
  await db.execAsync('PRAGMA foreign_keys = ON;')
  return new ExpoDbAdapter(db)
}

/**
 * The read-only bundled nutrition corpus.
 *
 * The artifact built by tools/nutrition-data ships as an app asset and is
 * imported into the SQLite directory on first launch, because FTS5 needs a real
 * writable path for its temporary files. The app never writes to it — the copy
 * exists for SQLite's benefit, not ours, and a corpus update replaces the file
 * wholesale rather than mutating it.
 *
 * WITHOUT THIS IMPORT the app opens an EMPTY database of the same name, and every
 * food silently falls to the AI-estimate path — which looks exactly like a
 * resolver bug while actually being a missing asset. Hence `nutritionCorpusInfo`
 * below, so that failure is legible rather than mysterious.
 *
 * THE STALE-COPY BUG THIS FUNCTION USED TO HAVE: `importDatabaseFromAssetAsync`
 * is idempotent by FILENAME — once a device has ever imported "nutrition.db",
 * it never re-copies it, on any later cold start, even across app rebuilds
 * that ship a rebuilt corpus with completely different content (better search
 * ranking, added data, whatever). A resolver fix verified working against the
 * bundled .db file could still show the OLD behavior on a device that had
 * already run any earlier build — silently, with no error, because the query
 * genuinely runs and returns real (stale) rows. `NUTRITION_DB_BUILT_AT` is
 * generated by the build script from the CURRENT asset; comparing it against
 * what's actually on disk is the only way to tell "unchanged, skip the copy"
 * apart from "changed, and the fast path is now lying."
 */
let nutritionChecked = false

export async function openNutritionDb(): Promise<DbAdapter> {
  if (!nutritionChecked) {
    nutritionChecked = true
    try {
      await SQLite.importDatabaseFromAssetAsync('nutrition.db', {
        assetId: require('../../assets/nutrition.db'),
        forceOverwrite: false,
      })
    } catch {
      // Already imported by a previous launch — the common path.
    }

    const onDiskVersion = await (async () => {
      try {
        const db = await SQLite.openDatabaseAsync('nutrition.db')
        const row = await db.getFirstAsync<{ value: string }>(
          "SELECT value FROM build_manifest WHERE key = 'built_at'",
        )
        await db.closeAsync()
        return row?.value ?? null
      } catch {
        return null
      }
    })()

    if (onDiskVersion !== NUTRITION_DB_BUILT_AT) {
      try {
        await SQLite.deleteDatabaseAsync('nutrition.db')
      } catch {
        // Nothing to delete — fine, importDatabaseFromAssetAsync below still runs.
      }
      await SQLite.importDatabaseFromAssetAsync('nutrition.db', {
        assetId: require('../../assets/nutrition.db'),
        forceOverwrite: true,
      })
    }
  }

  const db = await SQLite.openDatabaseAsync('nutrition.db')
  return new ExpoDbAdapter(db)
}

/**
 * Confirm the corpus actually arrived.
 *
 * A build shipped without the asset answers every query with zero rows, which is
 * indistinguishable at the UI from "no match found". Surfacing the row count
 * turns a silent, confusing failure into an obvious one.
 */
export async function nutritionCorpusInfo(
  db: DbAdapter,
): Promise<{ foods: number; portions: number; builtAt: string | null }> {
  try {
    const foods = await db.get<{ c: number }>('SELECT COUNT(*) c FROM foods')
    const portions = await db.get<{ c: number }>('SELECT COUNT(*) c FROM food_portions')
    const built = await db.get<{ value: string }>(
      "SELECT value FROM build_manifest WHERE key = 'built_at'",
    )
    return { foods: foods?.c ?? 0, portions: portions?.c ?? 0, builtAt: built?.value ?? null }
  } catch {
    return { foods: 0, portions: 0, builtAt: null }
  }
}
